version: 2.1

jobs:
  build:
    docker:
      - image: rust:1
    environment:
      HADOLINT_VERSION: 1.17.1
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Clone project
          command: |
            git clone --recursive https://github.com/dani-garcia/bitwarden_rs
            cd bitwarden_rs
      - run:
          name: Stable Build
          command: |
            rustup component add rustc
            rustup component add cargo
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: rustup run stable cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

workflows:
  build:
    jobs:
      - build
