version: 2.1

orbs:
    orb-tools: circleci/orb-tools@10.0

jobs:
    build:
        docker:
            - image: rust:1
        environment:
            HADOLINT_VERSION: 1.17.1
        steps:
            - run:
                  name: Clone project
                  command: |
                      git clone --recursive https://github.com/dani-garcia/bitwarden_rs ~/bitwarden_rs
                  working_directory: ~/bitwarden_rs
            - checkout
            - restore_cache:
                  key: project-cache
            - run:
                  name: Nightly Build
                  command: |
                      curl -L https://github.com/hadolint/hadolint/releases/download/v$HADOLINT_VERSION/hadolint-$(uname -s)-$(uname -m) -o /usr/local/bin/hadolint
                      chmod +rx /usr/local/bin/hadolint
                      rustup set profile minimal
                      rustup toolchain install nightly
                      rustup run nightly rustc --version --verbose
                      rustup run nightly cargo --version --verbose
                      rustup run nightly cargo build --features postgresql --manifest-path ~/bitwarden_rs/Cargo.toml
                      pwd
                      ls
            - run:
                  name: Nightly Test
                  command: rustup run nightly cargo test --features postgresql --manifest-path ~/bitwarden_rs/Cargo.toml
            - save_cache:
                  key: project-cache
                  paths:
                      - "~/.cargo"
                      - "./target"
workflows:
    build:
        jobs:
            - build
            - orb-tools/lint
            - orb-tools/pack
            - hold-for-dev-publish:
                  type: approval
                  requires:
                      - orb-tools/lint
                      - orb-tools/pack ~/bitwarden_rs/
            - orb-tools/publish-dev:
                  orb-name: <namespace>/<orb-name>
                  context: <publishing-context>
                  requires: [hold-for-dev-publish]
