version: 2.1

jobs:
  build:
    docker:
      - image: rust:1
    environment:
      HADOLINT_VERSION: 1.17.1
    steps:
      - run:
          name: Clone project
          command: |
            git clone --recursive https://github.com/dani-garcia/bitwarden_rs ~/bitwarden_rs
            cd ~/bitwarden_rs
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Stable Build
          command: |
            curl -L https://github.com/hadolint/hadolint/releases/download/v$HADOLINT_VERSION/hadolint-$(uname -s)-$(uname -m) -o /usr/local/bin/hadolint
            chmod +rx /usr/local/bin/hadolint
            rustup set profile minimal
            rustup toolchain install stable
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build --manifest-path ~/bitwarden_rs/Cargo.toml 
      - run:
          name: Test
          command: rustup run stable cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

workflows:
  build:
    jobs:
      - build
